name: Ubuntu Build

on:
  push:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: ubuntu_build
        path: ${{github.workspace}}/build/rtcamp2022
        
    - name: Render
      run: ${{github.workspace}}/build/rtcamp2022
      
    - name: Upload Rendered Image
      uses: actions/upload-artifact@v3.1.0
      with:
        name: output.png
        path: ${{github.workspace}}/build/output.png
      
