name: Ubuntu Build

on:
  push:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: switch to gcc-7 on linux
      run: |
        sudo apt install gcc-7 g++-7
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 100 --slave /usr/bin/g++ g++ /usr/bin/g++-7 --slave /usr/bin/gcov gcov /usr/bin/gcov-7
        sudo update-alternatives --set gcc /usr/bin/gcc-7

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        
    - name: Render
      run: ${{github.workspace}}/build/rtcamp2022
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: ubuntu_build
        path: ${{github.workspace}}/
      
